from . import fleet_vehicle_model
from . import product_template
from . import vehical_workshop
from . import hr_employee
from . import service_request
from . import job_card
from . import service_category
from . import service_type
from . import service_checklist
from . import service_packages
from . import job_timesheet
from . import work_order
from . import check_list_line
from . import job_card_checklist_line
from . import fleet_vehicle
from . import diagnosis
from . import package_service_line
from . import job_card_service_charge_line
from . import job_card_vehicle_spare_parts
from . import job_card_timesheet_line
from . import purchase_order
from . import sale_order
from . import job_images